### ISSUE TITLE
No longer able to enable short open tags from .htaccess files.

### ISSUE THREAD

**Issue by thinsoldier** [laravel/homestead#1357]
I used to be able to add this to the .htaccess files of specific apache legacy projects within Laravel Homestead to display errors and allow php's short tags

```
<IfModule mod_php7.c>
    php_value display_errors 1
    php_value short_open_tag 1
</IfModule>
```

This doesn't seem to work anymore in the latest Homestead.
Does anyone know how it's done now?

**Comment by svpernova09** [comment]
Instead of doing this with `.htaccess` you should set these options in the specific version of PHP you're using for the site. For example, if you're using 7.4, you'd want to set the options in `/etc/php/7.4/cli/php.ini`. You can see how we set [variables in settler](https://github.com/laravel/settler/blob/8cf78207f05f800ba9388d502ad49cd5d73cb929/scripts/provision.sh#L110-L113) for ideas on how to set your configuration.
