### ISSUE TITLE
Add entry to XDebug config to work with certain IDEs 

### ISSUE THREAD

**Issue by michapietsch** [laravel/homestead#1404]
Hey,

to make XDebug work with Visual Studio Code I always need to apped `xdebug.remote_autostart = 1` to `xdebug.ini`. I do so in my `after.sh`.

Maybe others can confirm this need? Also, can anybody say if there is a potential negative effect on other IDE's settings? If not, I suggest to enhance the default config accordingly. 

My best regards, Micha

**Comment by svpernova09** [comment]
If it's not going to adversely affect anything I'm good w/ making this change. Consider it on the TODO list.

**Comment by michapietsch** [comment]
@svpernova09 Thanks!

I never use a browser extension or bookmarklet like mentioned in the docs. As I mention in the PR, it's as easy as set a breakpoint, start a debug session, and load the page (or run the test).

**Comment by deviantintegral** [comment]
The one advantage of a cookie or other parameter is that you can more easily debug from only a single browser or session, without having to mute and unmute all your breakpoints. Perhaps an advanced use case, but it’s my guess why PHPStorm defaults to it in their docs: https://www.jetbrains.com/help/phpstorm/zero-configuration-debugging.html

You shouldn’t need auto start set for debugging to work at all with VS Code, since the ide shouldn’t care how the session was triggered. Can you confirm it doesn’t work when using a session parameter?

**Comment by michapietsch** [comment]
@deviantintegral 

> having to mute and unmute all your breakpoints

I don't mute my breakpoints. I just stop my VS Code debug session. What exactly do you mean?

> Can you confirm it doesn’t work when using a session parameter?

Previously I used PHPStorm and it worked out of the box. However with VS Code it's my experience that I always need to set this parameter. Nothing else but the scaffolded VS Code debug config and a path mapping.

@svpernova09 

> If it's not going to adversely affect anything

I got this answer from Derick Rethans, creator of Xdebug:
"Not as long as that VM has no access from anything but the host OS. (i.e, no access beyond the subnet that the host and guest are on)"
(https://twitter.com/derickr/status/1251992263049252872)

So I understand it should be disabled during sharing.

**Comment by svpernova09** [comment]
Hrm, that tweet concerns me, I replied.

**Comment by svpernova09** [comment]
> The one advantage of a cookie or other parameter is that you can more easily debug from only a single browser or session, without having to mute and unmute all your breakpoints. Perhaps an advanced use case, but it’s my guess why PHPStorm defaults to it in their docs: https://www.jetbrains.com/help/phpstorm/zero-configuration-debugging.html


100% agree I don't know if we're the minority or not. I'm tempted to leave this as is and instead add a commented example of how to enable this in `after.sh`.

> 
You shouldn’t need auto start set for debugging to work at all with VS Code, since the ide shouldn’t care how the session was triggered. Can you confirm it doesn’t work when using a session parameter?

I've spent actual *days* working to ensure Homestead 100000% *by default* works out of the box w/ Xdebug. I wanted us to be rock solid in this so the user who is frustrated trying to get this to work can *trust us* that we've done our part right and the issue is with their IDE/Editor. Because I've been that user way back in my career and I want to do my best to ensure someone else doesn't learn that way.

All of that to say I think we can take or leave this change. I just want to know what we're getting into if we enable this as default.

**Comment by michapietsch** [comment]
> add a commented example in `after.sh`

I like that. It's better for users to opt in.

> I've spent actual _days_

Appreciate it a lot! Also you taking the time now.

I realize that I'm not as close as deep into the matter than you. At some point I read up a bit, and ever since I set this option to get it working.

Running in the browser this option really toggles it working or not working for me.

I use this config inside `.vscode/launch.json`:

```
{
      "name": "Listen for XDebug on Homestead",
      "type": "php",
      "request": "launch",
      "pathMappings": {
        "/home/vagrant/code": "${workspaceRoot}"
      },
      "port": 9000
    }
```

But when running a PHPUnit test from the IDE it doesn't trigger. Still have to figure this out.

Debugging inside tests is the biggest reason for me to not rely on a browser extension.

> I just want to know what we're getting into

I see, and so should users if there's a potential issue.

It may be a little off-topic, but aren't there other security issues with sharing a VM, maybe even more severe? For example access to the `~/.ssh/id_rsa` if it's not passphrase-protected... (curious question, because again I realize you have more insight).

**Comment by deviantintegral** [comment]
Did you see the [xphp](https://github.com/laravel/homestead/blob/master/resources/aliases#L266) alias? I don't use it much myself, because PHPStorm has built-in support for enabling CLI debugging under vagrant VMs, but it may be useful if VS Code doesn't have that.

> For example access to the ~/.ssh/id_rsa if it's not passphrase-protected

It's really not any different than any software you run directly on the host. A malicious `vagrant | docker | MAMP | homested | homebrew | etc...` can grab anything that's unprotected and siphon it off.

**Comment by svpernova09** [comment]
> It may be a little off-topic, but aren't there other security issues with sharing a VM, maybe even more severe? For example access to the ~/.ssh/id_rsa if it's not passphrase-protected... (curious question, because again I realize you have more insight).

The only reason Homestead (the VM) has access to the private key is because we do have *read8 access to that file because it's assumed you're running `vagrant` as the owner of the private key.

Homestead *could* 100% do nefarious things with your private keys, but it just so happens our code is 100% open and browseable :D

**Comment by svpernova09** [comment]
I think I've changed my mind on this, I'm happy with the current implementation and I'm willing to accept a PR/MR which includes a commented out by default line in `after.sh` that enables this feature as an example to make this easier on our users who need autostart enabled.

Thanks all for the questions and the discussions! Always enjoyable.

**Comment by michapietsch** [comment]
Hey, quick follow-up, because it clicked for me when I watched Derick Rethans and Matt Stauffer stream:

My issue is related to the VS Code extension by Felix Becker. It requires `xdebug.remote_autostart = 1`, but as Derick told there: He always uses a browser extension to do the equivalent.

So this is also workflow-specific.
