### ISSUE TITLE
How to configure nginx default_server

### ISSUE THREAD

**Issue by DestinyHunter** [laravel/homestead#1429]
I need to set the default site, how should I configure default: true does not work

**Comment by svpernova09** [comment]
There is no way to set a default site in nginx. Because we don't this means the default site will be whichever site file is enabled that would come first based on the name. This means if you have `site1.dev`, and `test.dev` in your `Homestead.yaml` nginx *should* designate `site1.dev1 as the default.

**Comment by svpernova09** [comment]
If you're only checking emails, please click and re-read my comment above, it's late, I wrote a ton of typos. sorry. Hope this helps!

**Comment by DestinyHunter** [comment]
Is there an expected increase? If there is no such configuration, I change the site config and my configuration will be overwritten the next time homestead.yaml is updated,
I need to add default_server configuration every time

**Comment by svpernova09** [comment]
My two suggestions:

* In `after.sh` create a default site so it will be recreated every time you `vagrant up`

or

* If you don't have any sites that start with A, then create a site named `aaaaa.test` this site should be the "default"
