### ISSUE TITLE
Proposal: Switch PHP CLI version on enter a directory

### ISSUE THREAD

**Issue by Schnoop** [laravel/homestead#1526]
I have 20+ projects running in a single homestead instance. As all projects belongs to one customer is makes totaly sense in my case.
All these projects has been created over a few years and different PHP versions were used. For the webserver side this could easily behandled via the Homestead.yaml. But for the cli side this is a bit tricky. I have manualy to switch the PHP cli version depending on the project i'm working on - what i often forget. A composer update with the wrong PHP version can lead to a lot of problems.

I thought about something that changes the cli version if i enter a project directory. I've seen similar for node using the .nvmrc file: https://github.com/nvm-sh/nvm#nvmrc

Is this a useful approach for all homestead user or do you think this a special need in my case?

**Comment by svpernova09** [comment]
Sadly, what you're wanting doesn't exist (at least that I've been able to find and be happy with).  Primarily this is because PHP is often used around the idea there is *one* CLI SAPI that just exists, it's not part of an enviornment (Such as Ruby's RVM, Python's Virtualenv, etc). https://github.com/virtphp/virtphp Came close to getting this to a workable state for PHP but then fell off as side projects tend to do.

IMHO you're better off making yourself custom aliases to use to [update the PHP CLI version](https://github.com/laravel/homestead/blob/master/resources/aliases#L47-L51).

**Comment by svpernova09** [comment]
If you are interested in chasing down this idea I would try to follow what https://direnv.net/ does. I use it extensively for Python. You could do something similar and run your alias to swap PHP CLI.
