### ISSUE TITLE
Trying to install laravel/homestead vagrant box

### ISSUE THREAD

**Issue by TheWithout** [laravel/homestead#1583]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
  - Vagrant: 2.2.14
  - Provider: VMWare
  - Homestead: -

## Host operating system
macOS Big Sur 11.1

## Expected behavior
option for vmware_desktop is disabled/removed and unable to install vagrant box for v9.7.2

## Actual behavior
install via option vmware_desktop

## Steps to reproduce
![image](https://user-images.githubusercontent.com/48665103/103169204-a82f2400-4874-11eb-8175-7331f00fb223.png)

**Comment by svpernova09** [comment]
(My info may be outdated)

on macOS you don't have access to `vmware_desktop`, AFAIK it's only Fusion on macOS. the `vmware` option there should work for you.

**Comment by TheWithout** [comment]
> (My info may be outdated)
> 
> on macOS you don't have access to `vmware_desktop`, AFAIK it's only Fusion on macOS. the `vmware` option there should work for you.

vmware doesn't work on Fusion macOS, need to be vmware_desktop.

![image](https://user-images.githubusercontent.com/48665103/103172955-6ca35280-4892-11eb-95c0-c5ddb43f8e8e.png)

**Comment by svpernova09** [comment]
Based on https://www.vagrantup.com/docs/providers/vmware/usage what you're trying to do should be:

```
$ vagrant box add laravel/homestead --provider=vmware_desktop --box-version=9.7.2
```

By running that command I noticed the actual issue is I've labeled the https://app.vagrantup.com/laravel/boxes/homestead/versions/9.7.2/ as `vmware` instead of `vmware_desktop`. I've updated the provider:

![image](https://user-images.githubusercontent.com/967362/103173145-7d19e580-481e-11eb-9ca6-41cdc67590ff.png)

And now running the above command downloads the box as expected. You can see my first attempt as well:

![image](https://user-images.githubusercontent.com/967362/103173177-a89cd000-481e-11eb-80d4-67515fbbe692.png)

Run this command, let me know if it's still broken. Thanks for the repot.
