### ISSUE TITLE
Issue when provisioning vagrant - homestead.test not working...

### ISSUE THREAD

**Issue by benpoarch** [laravel/homestead#1585]
Get the following error when I run vagrant up:

==> homestead: Running provisioner: Update Composer (shell)...
    homestead: Running: script: Update Composer
    homestead: You are already using composer version 2.0.8 (stable channel).
    homestead: chown: 
    homestead: cannot access '/home/vagrant/.composer/'
    homestead: : No such file or directory
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

My homestead.test says that there's "no input file specified" and when I vagrant up it says the machine is already provisioned, then telling me to run the above command. I've tried deleting VMs and creating a new one and it just says its already provisoned straight away. I need this fixed ASAP its been days and my deadline is monday!

**Comment by svpernova09** [comment]
> I need this fixed ASAP its been days and my deadline is Monday!

I'm available to hire to solve your problems for $200/ hour (1-hour minimum + a 50$ weekend surcharge).

> Get the following error when I run vagrant up:
> 
> ==> homestead: Running provisioner: Update Composer (shell)...
> homestead: Running: script: Update Composer
> homestead: You are already using composer version 2.0.8 (stable channel).
> homestead: chown:
> homestead: cannot access '/home/vagrant/.composer/'
> homestead: : No such file or directory
> The SSH command responded with a non-zero exit status. Vagrant
> assumes that this means the command failed. The output for this command
> should be in the log above. Please read the output to determine what
> went wrong.
> 
> My homestead.test says that there's "no input file specified" and when I vagrant up it says the machine is already provisioned, then telling me to run the above command. I've tried deleting VMs and creating a new one and it just says its already provisoned straight away. 

Based on your previous efforts of ignoring instructions in #1584 and now this issue, I'm going to guess you're probably still having issues with paths being mapped into the VM. (`homestead: cannot access '/home/vagrant/.composer/'` )

Until you provide the information we need to help you (Hint: you've deleted all the instructions TWICE now when creating your issues) no one can help because we're missing all the things that help us debug issues.
