### ISSUE TITLE
NFS not supported for windows

### ISSUE THREAD

**Issue by ivanradojevic-web-dev** [laravel/homestead#1586]
I try to install npm, but have erros and find soultion to put nfs to homestead.yaml file. I do that, but NFS is not supported. What is the soultion of this problem?
```
It appears your machine doesn't support NFS, or there is not an
adapter to enable NFS on this machine for Vagrant. Please verify
that `nfsd` is installed on your machine, and try again. If you're
on Windows, NFS isn't supported. If the problem persists, please
contact Vagrant support.
```

**Comment by svpernova09** [comment]
I have no idea because you completely ignored the issue template.

> I try to install npm

NPM is already installed. You don't need to install it.

If NFS is the answer you're probably asking the wrong question. My guess is you're likely having issues with *npm install* on Windows because of the annoying Virtualbox bugs with their shard folders.
