### ISSUE TITLE
Per project directory vs one single directory for all projects issue.

### ISSUE THREAD

**Issue by Wintersunner** [laravel/homestead#1862]
## Versions
  - Vagrant: 2.34
  - Provider: Parallels v18.1.1.
  - Homestead: latest

## Host operating system
MacOS M2 Ventura 13.2.1

## Problem

It's highly recommended in the homestead documentation not to map one big directory e.g. Code for all the projects inside it and instead to map projects one by one in the homestead yaml file. The problem with the latter approach is the `code` directory will be owned by `root` in VM and you can't create laravel projects from inside the homestead machine.

Even if you change the permissions manually and create laravel project inside homestead, because it's first created in the virtual machine it won't be mounted from other way around and you'll get `homestead: Unable to mount one of your folders` while reloading the vagrant.

The workaround would be to create the project on the host machine and then map the directory in homestead file, which will be only doable if you install php and composer on the host that is unnecessary

or

if you create an empty directory first in the host machine then map it in yaml file and then put the project files inside that in VM.

You don't have to deal with all these if you just map the whole code directory to the code directory of the host. Just wanted to know is there any workaround to this? am I missing something?

**Comment by Sn0wCrack** [comment]
I'm not entirely familiar with Parallel's default folder mounting mechanisms, but I do know that if you try `nfs` as your folder type it should maintain the file permissions and ownership of your local machine when files are created from within Homestead and moving files into it should remap to your local file permissions and ownership.

Personally as well for my workflow with mount-per-project, I create my projects on my local machine rather than in Homestead itself.
I rarely find myself creating files from within Homestead itself and move them into mounted directories.

If you are going to attempt to use the `nfs` folder type you'll wanna make sure you give the `/sbin/nfs` binary "Full Disk Access" permissions.

**Comment by svpernova09** [comment]
Parallels has the fastest folder mapping I've seen as an end user. The "Don't map 1 large directory" is less of a problem these days. My rule of thumb has always been to only map what you need into the VM. Some people have mapped hundreds of projects and never had an issue. Your milage may vary based on your host system.
