### ISSUE TITLE
Stepping down as maintainer.

### ISSUE THREAD

**Issue by svpernova09** [laravel/homestead#1977]
```
MIME-Version: 1.0
Date: Tue, 22 Aug 2023 13:12:22 -0500
Message-ID: <CABj1BaYvjUGyRhrsis9Z2U9yMQGUt_YTbV54cjcV0Au_3uNDiA@mail.gmail.com>
Subject: Homestead & Settler
From: Joe Ferguson <joe@joeferguson.me>
To: Taylor Otwell <taylor@laravel.com>
Content-Type: multipart/alternative; boundary="000000000000bcc068060386ef58"

--000000000000bcc068060386ef58
Content-Type: text/plain; charset="UTF-8"

Hi Taylor,

Hope things are well. I've just published Homestead v14.4.2 which is likely
the last release. I've resolved all the glaring issues brought up in the
past year. I think it's time to call Homestead done. It served a great
purpose really well and still continues to.

Feel free to archive these repositories. People can happily fork to their
heart's content.

Thanks for trusting me with this. I learned a lot and messed up a lot.

-- 
- Joe Ferguson
JoeFerguson.me
osmihelp.org
```

thanks for the ride, everyone.

**Comment by browner12** [comment]
I would be interested in taking over the project. I still believe Homestead is a great solution for local development, and want to continue the great work Joe has done over these many years.

**Comment by rayblair06** [comment]
Thank you for your contributions as the maintainer of Homestead, @svpernova09. It goes without saying that your work has made a significant impact on the Laravel community, making it easier for developers like myself to work with Laravel. Wishing you all the best in your future endeavours.

**Comment by wallacio** [comment]
@svpernova09 Joe - thanks so much for your work in keeping this current for so long. I depend on Homestead for so many projects (not just Laravel); it's a one-stop shop that's been so easy to use.

Hopefully this isn't the end of Homestead, I'd love to see someone else take on maintenance of it.

**Comment by Sn0wCrack** [comment]
Don't know what to say that hasn't been said, but thank you for all the work on Homestead over the years.

It's allowed myself and everyone on my team to deliver some awesome stuff due to the simplicity and customisability of it. Adding new software to our multi-project stacks being as simple as changing a value `true` has been an awesome feeling, especially considering we used to run our stuff under WAMP not even 5 years ago now, it's been a world of difference.

I do hope we can see a continuation of this project within the Laravel ecosystem and I'm honestly happy to help out where I can if it means keeping this amazing project alive.

**Comment by Erulezz** [comment]
Thank you @svpernova09 for all the hard work and for maintaining it all these years. I used it a lot so again, thanks 🥇

**Comment by svpernova09** [comment]
No one panicked, right? 😅 

https://github.com/svpernova09/settler

v14.1.0 base boxes for Parallels (x86_64 & aarch64/arm64) and Virtualbox (x86_64) [have been released](https://app.vagrantup.com/Svpernova09/boxes/homestead).

https://github.com/svpernova09/homestead

The `main` branch is updated, but there is no tag yet. If you're brave, clone it and throw your `Homestead.yaml` as is and `vagrant up`. Yell if anything breaks, then open a [new issue](https://github.com/svpernova09/homestead/issues/new).

**Comment by Sn0wCrack** [comment]
So what exactly has happened then @svpernova09? I'm a bit confused here.

**Comment by svpernova09** [comment]
> So what exactly has happened then @svpernova09? I'm a bit confused here.

Homestead hasn't been a priority for Laravel in a long time. If users want to keep using Laravel Homestead, it will be fine for a while, as most of us know it's a pretty solid tool. Laravel could appoint a new maintainer to take over. I tried to leave things better than I found them.

If users want to continue using an up-to-date version of Homestead, they should migrate to my fork.

**Comment by Erulezz** [comment]
> Homestead hasn't been a priority for Laravel in a long time.

That's something I don't understand, it's such a great development tool and I still prefer it after all these years over the newer "official" tools

**Comment by oliverquynh** [comment]
Thank you for all your work on Laravel Homestead! Wish you the best!

**Comment by oliverquynh** [comment]
> I would be interested in taking over the project. I still believe Homestead is a great solution for local development, and want to continue the great work Joe has done over these many years.

@browner12 Thank you so much! Have you tried to reach Taylor to tell him you want to take responsibility on this project?

**Comment by skeeith** [comment]
@browner12 @svpernova09 I too would love to be one of the maintainers of homestead, I've contributed in the past on this project as well, and as of today I still prefer Laravel Homestead as my local development environment over the newer official tools.

I've been using it since Laravel v5 (2016) days, and for me it's still way better and easier. not only that, it's also way flexible and easier to upgrade/change anything you want in your environment as it's literally a local server where you can tinker to your hearts content.

@svpernova09 if it's okay with you, could you introduced me, @browner12, and whoever here is interested to @taylorotwell to be the new maintainers of Laravel Homestead. I do believe Laravel Homestead has more to offer to our community still

here's my email address `gether.medel@gmail.com`

**Comment by skeeith** [comment]
@svpernova09 about the panicking part, I'm about too 😂 as I've been using it ever since and even until now, the amount of ease it gives me still has no comparison, especially if you're handling multiple projects? just opening those local custom domain names after running vagrant up is easier than running multiple docker commands just to run multiple projects.

it gives you that actual behavior on your local env, especially if you have sub domains running on some projects.

so I say, Laravel Homestead still has more to offer in our community. You might feel that they're not giving much attention to Laravel Homestead, and the reason probably is because it's that stable already and it doesn't needed to be looked after much, but there's still A LOT of people in our community who are actually still dependent on this.

**Comment by wsamoht** [comment]
Well, I am confused 🤔😅 Joe said he is stepping down (greatly appreciate all your work!) but has forked the repos and is continuing to maintain his own forks. I am curious why this is the case and why not just keep maintaining the Laravel repos.

I know the Laravel team is focused on Laravel Herd but I am among the Linux users and apparently there is no current plans to support Linux.

From [Laravel Herd's website FAQs](https://herd.laravel.com/):

> **Is there a Linux version available?**
> There are currently no plans for a Linux version of Herd, and we believe that Linux users are more comfortable installing and running their development environment in general. We regularly evaluate our decisions and this might change in the future.

Sure, I could install everything locally but the reason I use Homestead is so I don't pollute my local environment.

Taylor also said in the recent [Live Q&A](https://www.youtube.com/live/UV5KGJRN1gk?si=HDg0zmO7Ksn6u_WO&t=2616) that Herd for Linux is not on the short term road-map.

It would be nice to hear from Taylor or another Laravel team member regarding the future of Homestead. Are we supposed to jump to Joe's new forks?

**Comment by taylorotwell** [comment]
Hi all! We don't plan to contribute anymore time to Homestead on our end. Thanks @svpernova09 for your efforts!

Of course, since Homestead is open source, anyone is free to fork and continue maintenance. ❤️

**Comment by skeeith** [comment]
@wsamoht apparently we don't know what's the plan on Homestead right now though. The problem with Herd is that most of the advance features are lock behind payment well, unlike Homestead were everything is free. Even just using the most common DBs we're used to using is locked behind the Pro version

`Herd ships with PHP extensions to support for all major databases, so if you're using MySQL, PostgreSQL, MongoDB, Redis or SQLite, we've got you covered. New Laravel applications use SQLite as default, and you don't need an additional database service to get up and running.`

`If you plan to use MySQL, PostgreSQL, MongoDB or Redis, you can either download the database service from its vendor, use a free tool like DBngin to manage the database service or upgrade to Herd Pro.`

`Herd Pro provides a convenient user interface to manage services for MySQL, PostgreSQL, MongoDB, Typesense, Meilisearch, MinIO, and Redis, and Laravel Reverb and you can get them up and running in seconds.`

This one sounds like a red flag to be honest. even just trying to develop the application locally requires you to pay for it.

**Comment by skeeith** [comment]
@taylorotwell can you share a little bit of insight on what's the future for Homestead? cause to be honest Homestead is still the best working environment for Windows.

**Comment by svpernova09** [comment]
> @taylorotwell can you share a little bit of insight on what's the future for Homestead? cause to be honest Homestead is still the best working environment for Windows.

He already did. he plainly said 

> We don't plan to contribute anymore time to Homestead on our end

If you want something from the same person who has been working on Homestead for the past eight years I recommend you migrate to [my fork](https://github.com/svpernova09/homestead).

**Comment by browner12** [comment]
Even though I knew this was coming, I still have to voice my displeasure.

Homestead has been the best local development environment in the Laravel ecosystem since it was introduced.

**Comment by svpernova09** [comment]
> Even though I knew this was coming, I still have to voice my displeasure.
> 
> Homestead has been the best local development environment in the Laravel ecosystem since it was introduced.

I get it. But the software works the same even at a different top-level org/name. :)

**Comment by browner12** [comment]
Yup, and I'll definitely be migrating over eventually.  It's just nice to have an organization behind a product so you can ideally get resources and support from a team, rather than an individual.

IMO this is a huge miss for Laravel.

**Comment by svpernova09** [comment]
> Yup, and I'll definitely be migrating over eventually. It's just nice to have an organization behind a product so you can ideally get resources and support from a team, rather than an individual.
> 
> IMO this is a huge miss for Laravel.

Outside of the documentation and the fantastic contributors, no one employed by Laravel has worked on Homestead since 2016. I have done all the releases and base box builds, so the idea that a team was behind it wasn't accurate.

**Comment by browner12** [comment]
Hah, I know. Somedays it just felt like you and I in here talking to ourselves. 😅 

I just *wish* there had been more resources from the organization committed to this fantastic product.
