### ISSUE TITLE
VMware (Windows) and IP Allocation

### ISSUE THREAD

**Issue by jordanramstad** [laravel/homestead#375]
This is not so much a bug as it is just a provider issue (at least I think). 

If you set an IP for the homestead box, the VMware provider will ignore it and use its own random IP. I have tested this on 2 different Windows 10 machines and its the same result on each on. I have used the most current version but this is something that has been around since I first started using Homestead. 

### Vagrant version
Vagrant 1.9.0

### Provider & Provider version
VMware Workstation 12.5.2 build-4638234

### Host operating system
Windows 10

### Homestead.yaml
Simplified with the main relevant information
```yaml
---
ip: "192.168.50.10"
memory: 2048
cpus: 1
hostname: homestead
name: homestead
provider: vmware_workstation
mariadb: true
gui: true
```

### Vagrant up output
Narrowed to the relevant area.
```
    homestead: Waiting for machine to boot. This may take a few minutes...
    homestead: SSH address: 192.168.126.129:22
    homestead: SSH username: vagrant
    homestead: SSH auth method: private key

```

### Expected behavior
IP should be the one entered in the `Homestead.yaml` file.

### Actual behavior
A random IP was assigned to the VM

### Steps to reproduce
1. Use the same setup (Windows, VMware Workstation)
2. Set a custom IP for the box in the `Homestead.yaml`
3. Launch the machine.

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
None that I could find.

**Comment by svpernova09** [comment]
I'll look into this some. If it does come down to a provider issue then it's obviously out of our hands, but I'll get the docs updated to mention it.

Thanks!

**Comment by svpernova09** [comment]
From what I've read this sounds like it's primarily and issue with the VMWare network virtualization. It's treating every new VM it boots as a different computer on the network (Which sure, why wouldn't it?). 

Try adding this to `Homestead.yaml`:

```
networks:
    - type: "private_network"
      ip: "192.168.10.11"
```

Adjust the IP to something suitable so long as it's not the same IP you have at the top of the config file.

`vagrant destroy && vagrant up` and see if the VM comes up with a secondary interface using `192.168.10.11`. If so great, that's the workaround. I'm not super confident that will solve the issue.

Another response I read about mentioned specifying a MAC to the interface so that you can assign a static IP in the VMWare network settings.

Let me know if either of these options helped.

**Comment by jordanramstad** [comment]
The network solution seems to work! I have not tried the second one but it does seem far more involved then adding an additional network.

I reloaded and destroyed and remade just to be sure and it seems to persist without a problem.

Thanks You.

**Comment by svpernova09** [comment]
Awesome!
