### ISSUE TITLE
Installing Homestead on Digital Ocean droplet.

### ISSUE THREAD

**Issue by Modelizer** [laravel/homestead#393]
I tried installing homestead on digital ocean droplet using [digital ocean plugin for vagrant](https://github.com/devopsgroup-io/vagrant-digitalocean) But no success. This is my `Vagrantfile`

```bash
Vagrant.configure('2') do |config|

  config.vm.define "hot-shot" do |config|
      config.vm.provider :digital_ocean do |provider, override|
        override.ssh.private_key_path = '~/.ssh/vagrant_rsa'
        override.vm.box = 'digital_ocean'
        override.vm.box_url = "https://atlas.hashicorp.com/laravel/boxes/homestead/versions/1.0.1/providers/virtualbox.box"
        provider.token = 'lorm-ipsom'
        provider.image = 'ubuntu-16-04-x64'
        provider.region = 'blr1'
        provider.size = '512mb'
      end
  end

end
```

Please let me know what am I missing? Thanks 👍

**Comment by svpernova09** [comment]
You should not install Homestead on a digital ocean droplet since vagrant is inherently insecure and should be me put out onto the public Internet.

While you can use vagrant to control boxes out on the public Internet that is outside the scope of the Homestead project.

**Comment by Modelizer** [comment]
I want to use SSL certificate which should be publicly available and also I need my dev environment to be replicated to digital ocean droplet which is a test server. In this case to save some time it's easy you'll get everything you need in homestead will be available quickly.

**Comment by svpernova09** [comment]
If you would like an easy to use Test server you should use [Laravel Forge](http://forge.laravel.com). This way you can have a similar environment to the local Homestead.

**Comment by jordanramstad** [comment]
Forge also can do auto deploy, so when you commit to the right branch it can auto deploy to forge, making it fairly seamless.

Homestead/Vagrant is built with a mindset to "forget security" (since it assumes its only accessible on your LAN) It basically just does the bare minimum just so you can get your local test environment going without hitting any walls.

There is ways to temporarily make your local "live" even using https https://ngrok.com/ There is a number of services like this that can make a tunnel to your local if you need to do things like webhook testing.

Although I don't use it Docker is another solution, homestead cannot run on it but setup correctly you can use the same containers for live and local.

**Comment by Modelizer** [comment]
@jordanramstad nice solution! Thanks 👍 

@svpernova09 Forge is too expensive man :)
