### ISSUE TITLE
Consider folder mount SMB as default option for Windows

### ISSUE THREAD

**Issue by lioannou** [laravel/homestead#403]
## Versions
  - Vagrant: 1.9.0
  - Provider: VMWare Workstation 12.5.2
  - Homestead: 4.0.2

## Host operating system
Windows 10

## Homestead.yaml
The problem is with the default `Homestead.yaml` file

## Vagrant up output
n/a - works ok

## Actual behavior
The VM fires up, and everything seems ok at first. But if you browse to a shared folder, the symlinks are not working correct, and neither is Git. You get strange network IO issues intermittently as well.

## Steps to reproduce
1.  `Vagrant up`
2.  `Vagrant ssh`
3. Go to your shared folder and type doing `git clone https://github.com/laravel/laravel test` - it will fail with an error

I've spent ages on this problem. It is a change in behavior from the 0.4.* boxes where this would all work correctly. I even put a 500 bounty on this SO question to try and get the answer - but with no luck; http://stackoverflow.com/q/33393077/1317935

Tonight I've discovered that explicitly setting the folder to `smb` sync in the `Homestead.yaml` file fixes everything.

From

```
folders:
    - map: ~/Code
      to: /home/vagrant/Code
```

to

```
folders:
    - map: ~/Code
      to: /home/vagrant/Code
      type: smb
```

So is this a "bug"? i.e. should Homestead default to `smb` on a Windows box? Is that possible?

At the minimum we would need to modify the Homestead documentation to state this is a requirement for Windows users - but it would be better if we can just make this the default for people on a Windows box?

The is one small change in behavior - because you are using `smb` then Vagrant prompts for your Windows username + password on the *first* provision of the box. Running `vagrant provision` subsequent times does not re-prompt, unless you `vagrant destroy`.

**Comment by svpernova09** [comment]
Thanks for the report. For those unaware this a bug @lioannou has been chasing since we released box version 0.6.x. We've both spent a ton of time debugging this and I'm unable to reproduce the error locally (Since I'm not using VMware Desktop, only Fusion).

I've had another person successfully reproduce the issue however the only way to reliably reproduce the issue was to use `vagrant suspend`. So my advice previously was "Use `vagrant halt` instead of `vagrant suspend`" since this walks and talks like a Provider (VMWare) bug. 

The only VMware related change Homestead has made since the noted previous working box version (0.4.x) was that the package `open-vm-tools` no longer contained the proper executable (`vmware-config-tools.pl`)to install the VMware tools. We stopped using `open-vm-tools` and started manually installing the VMware tools: https://github.com/laravel/settler/commit/1fed2ae37dac9fb890c75299b98a0827100eee68 We also jumped from Ubuntu 14.04 to Ubuntu 16.04 (if that matters to VMware). Nothing else has changed (on Homestead's end).

I'm glad you found a solution by using the Samba share type. This is probably less performant than the VMware default sharing. I wouldn't want to make this the default for Windows because you're (so far) the only user reporting this issue. This is also why I would not call using `smb` a requirement for Windows users.

Side note: Using Git primarily from within Homestead is possible, however I don't reccomend it for normal day to day workflow.

If we see a number of Windows users reporting this issue I'd be happy to work out a way to default the share type to `smb`, however right now it just doesn't seem like this is a major problem. Windows Users: please speak up. I would like to do what I can to make Homestead as easy to use on Windows as it is on MacOS and Linux.

Thanks.

**Comment by jonnywilliamson** [comment]
@lioannou Sorry for the trouble as well, but it's definitely not a bug that affects all windows users.

I've been using virtualbox and homestead on a windows 10 machine last year or so (and before that windows 7) and I've never needed to add smb to the options for a shared folder.

Ironically I did put them in my yaml file in case I ever needed had problems and I knew I would forget what the flag was, but to this day I haven't needed them.

Would this reenforce the idea that this is strictly a vmware related bug?

![image](https://cloud.githubusercontent.com/assets/2513663/21409396/ebc666e2-c7d1-11e6-908d-af090e7e86a2.png)

**Comment by jonnywilliamson** [comment]
FYI @svpernova09 I'm strictly a windows user with homestead. If I can help let me know.

**Comment by svpernova09** [comment]
> Would this reenforce the idea that this is strictly a vmware related bug?

Yeah. AFAIK it's only with VMware on Windows.

> I'm strictly a windows user with homestead. If I can help let me know.

Thanks!

**Comment by lioannou** [comment]
Thanks @jonnywilliamson 

It is only for VMWare. It works fine for me in Virtualbox using 1.0.1.

**Comment by lioannou** [comment]
@jonnywilliamson @svpernova09 - Forget the `git` issue - this fails when using the native mount:

`ln artisan test`
"ln: failed to create hard link 'blah' => 'artisan': Operation not permitted"

But if I do that same command when using the `smb` mount - it works.

I'll keep digging...

**Comment by gandesc** [comment]
I can confirm it's not working for me either, with the following configuration:
windows 8.1
vmware workstation 12.5.5
homestead 5.1.0
vagrant 1.9.3

On a different computer with the same setup but virtualbox instead of vmware, it git clone works.
