### ISSUE TITLE
Stuck on raising network interfaces

### ISSUE THREAD

**Issue by DrowningElysium** [laravel/homestead#576]
I am currently using the latest Homestead repo and the hyper-V 2.1.0 box, the problem I am currently having is that I can't connect to the box as it is stuck on the "A start job is running for Raise network interfaces" After the 5 minute timeout it will give up and the box is not connected to the internal network

**Comment by svpernova09** [comment]
What version of Vagrant are you using? There was a few issues around Windows (Networking and folder sharing IIRC) that were solved by 1.9.4/5

**Comment by DrowningElysium** [comment]
I am using 1.9.4, I did some fixes needed but will try 1.9.5

**Comment by svpernova09** [comment]
Cool. Hopefully that solves it because I can't offer any alternatives :/

I think I'm going to drop support for hyper-v and remove the published boxes. The developer experience people have become accustomed to from Homestead can't be maintained at this time via hyper-v. So instead of doing hyper-v badly, I'll wait until we can do it well.
