### ISSUE TITLE
Serve Command Documentation

### ISSUE THREAD

**Issue by 19peaches** [laravel/homestead#660]
I just recently botched my local Homestead version so I had to start from scratch.

I updated everything, Homestead to version 6.1, Box version to 3, Vagrant and Virtualbox, so I'm running all the lastest versions.

The normal install went fine, but in Homestead I now see there many different serve command scripts, with zero documentation that I can find for using all these cool scripts.

For instance, using the normal serve-laravel script via the alias serve, the nginx block for PHP is incorrect since the script itself is looking for a param to be passed for the PHP version ... there is no documentation for this on how to pass it in manually, or where it should be set globally so it doesn't need to be passed.

At the very least there should be a full list of all possible variables for the Homestead.yaml file, and all the different serve scripts, and how to execute them.

I've had to manually change the serve-laravel script so it correctly uses PHP 7.1, and sadly that has to be redone every time Homestead has a version bump.

If there is documentation can someone please point me to it?

Thanks

**Comment by svpernova09** [comment]
We don't document these because you shouldn't _need_ to run these serve commands yourself. Homestead will do it for you based on your Homestead.yaml settings.

If you do want to run these yourself then yes, you should be able to parse what's needed by looking at homestead.rb and seeing where they are called. You must pass a PHP version.

--
- Joe Ferguson
JoeFerguson.me
MemphisPHP.org

**Comment by 19peaches** [comment]
Where would I find the homestead.rb file on a Mac install? I don't see it in the Homestead directory.

**Comment by svpernova09** [comment]
https://github.com/laravel/homestead/blob/master/scripts/homestead.rb
