### ISSUE TITLE
VMware virtual machine clone location

### ISSUE THREAD

**Issue by envas** [laravel/homestead#763]
According to the vagrant docs the directory where the provider clones the virtual machine can be customized by setting the VAGRANT_VMWARE_CLONE_DIRECTORY environmental variable. However, Homestead clones are always located in the default location (the ".vagrant" folder relative to the folder where the Vagrantfile is), even with env variable set.

How can I force Homestead to change the VM files location?

**Comment by svpernova09** [comment]
This is a Vagrant environment configuration variable, Homestead should respect it (since it doesn't do anything to override this).

Add `export VAGRANT_VMWARE_CLONE_DIRECTORY="/path/you/want"` to your environment configuration and then all of the Vagrant boxes will be stored in `/path/you/want/*`. You'll probably have to destroy & up to have an existing vm moved to the new location.
