### ISSUE TITLE
Pick a specific version of database (older or current)

### ISSUE THREAD

**Issue by Dranac** [laravel/homestead#828]
Hello there,

I wonder if it would be doable to manage the version of the database picked in homestead.

Currently I'm having an issue where I'm forced to use a Postgresql 9.6 and it seems that the only two way of doing it is to uninstall the current postgresql then install 9.6 or getting an older homestead box then upgrade to 9.6 (but the idea of getting old box isn't really appealing).

So, is something like a version picker for database (even basic choices like, current version + previous major version available) would be something useful ?

**Comment by svpernova09** [comment]
Because we install Postgres upstream, this feature would have to remove the current version before doing anything. The implementation should be along the lines of how we allow specific versions of Elasticsearch: https://github.com/laravel/homestead/blob/master/scripts/homestead.rb#L334-L341 and https://github.com/laravel/homestead/blob/master/scripts/install-elasticsearch.sh#L18-L22

**Comment by svpernova09** [comment]
Closing this issue for now. Happy to reopen to discuss PR implementation.
