### ISSUE TITLE
New configuration for mongo databases

### ISSUE THREAD

**Issue by simonschaufi** [laravel/homestead#875]
I have a lot of projects with lots of mysql databases in my homestead box and only one project needs mongo. I see that I can enable mongodb globally but then I get a mongo database for all my projects.

I would find it much more useful to have a separate config for mongo-databases only.

**Comment by svpernova09** [comment]
I've thought about this a few times but never really came to a solution that I was happy with. The easiest solution I envision would be specify a DB Server / Provider for each database. I'm not thrilled because this would add a bit of complexity to `scripts/Homestead.rb` or each of the DB's bash scripts (potentially both).

I could see the use case and I would welcome any PRs taking a shot at this. However I will mention our current philosophy of "create a database on all installed DB systems" is somewhat of a canary in the coal mine for my personal testing of Homestead features. If we add the feature it would have to default to the "do not create db if system is mysql" option so that we still create on every provider so we can smoke test that default install is working with and without addon database servers.
