### ISSUE TITLE
Default MYSQL charset for databases created in command line

### ISSUE THREAD

**Issue by Nkoyan** [laravel/homestead#888]
When i add a database in homestead.yaml the charset used is `utf8mb4_unicode_ci`, but when i create a database in command line with `CREATE DATABASE laravel;` the charset is `latin1_swedish_ci`.
It would be nice if the defaut MYSQL settings match homestead settings.

**Comment by AgusRdz** [comment]
@Nkoyan you can try appending this:
```
[mysqld]
character-set-server=utf8mb4
collation-server=utf8mb4_bin
```

to `~/.my.cnf` then 
`sudo /etc/init.d/mysql reload`
`sudo /etc/init.d/mysql restart`

Also, you can check if the new configurations are taking effect running `mysqld --print-defaults`, if are not present in the output maybe you need to edit `/etc/mysql/conf.d/mysql.cnf` instead of `~/.my.cnf`.
